### ISSUE TITLE
projector scale mode

### ISSUE THREAD

**Issue by Ataraxxis** [vs-ude/mic-1-toolbox#109]
scale fonts by 175% - 200%
scale svg fonts by same amount
dont scale buttons

**Comment by YasinKavuk** [comment]
Now it does have a toggle switch for switching to "presentation mode". In this mode the font-size in in the editors, console, stack view and Register View get bigger. 
Only enhancement missing is the still scaling buttons, if we scale with the browser(or STRG and +). This enhancement may be not necessary because we don't have the need to scale with the browser anymore. 
Can be closed if this missing enhancement is not needed.
